### ISSUE TITLE
Alinhamento dos destaques pequenos

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/IDG-WP#12]
Quando existem menos de 3 destaques, o destaque fica alinhado a esquerda:

![photo_2019-04-22_15-08-00](https://user-images.githubusercontent.com/971483/56516029-ce34ea80-650f-11e9-8e2f-ddd95585048c.jpg)

Fazer ficar alinhado ao centro:

![photo_2019-04-22_15-08-02](https://user-images.githubusercontent.com/971483/56516037-d2f99e80-650f-11e9-8680-735a24b69476.jpg)

**Comment by leogermani** [comment]
pode-se usar a classe `justify-content-md-center`

**Comment by alvinodigo** [comment]
Feito na branch alinhamentoDestaques
