### ISSUE TITLE
Menu não ajusta altura ao conteúdo.

### ISSUE THREAD

**Issue by mateuswetah** [culturagovbr/IDG-WP#3]
O menu principal parece não ajustar a altura ao seu conteúdo:
![image](https://user-images.githubusercontent.com/1184874/56136470-3d876900-5f69-11e9-914e-243de75865e5.png)

E de um ponto de vista mais de design... faz sentido essa redundância aí das categorias do menu estarem logo acima como links? Também me gera uma confusão do "Acesso à informação" que aparece aí e na barra do gov.

**Comment by alvinodigo** [comment]
Altura do menu corrigida. Falta ver a questão da redundância.
