### ISSUE TITLE
Barra não aparece em HTTPS

### ISSUE THREAD

**Issue by Lopan** [culturagovbr/IDG-WP#31]
Pessoal, parabéns pelo trabalho com o template para wordpress.

Percebi que a barra do governo não aparece quando o site está em https, foi necessário um ajuste simples em: https://github.com/culturagovbr/IDG-WP/blob/135f6a087f57e2cd012a5618808d6c82c546d835/functions.php#L118

sendo necessário modificar a linha para

`wp_enqueue_script( 'barra-brasil-script', '//barra.brasil.gov.br/barra_2.0.js', false, false, true );`

**Comment by leogermani** [comment]
Oi @Lopan , muito obrigado pelo alerta! Não quer fazer um Pull request?

**Comment by Lopan** [comment]
@leogermani, vou tentar fazer aqui!
