### ISSUE TITLE
Alto contraste mal formado

### ISSUE THREAD

**Issue by Darciro** [culturagovbr/IDG-WP#9]
O print abaixo é [esta página](http://cultura.gov.br/documentos/leituragerafuturo-edital-1-bibliotecas-digitais-2018/) de notícia com o alto contraste ativado. Note que os nomes dos documentos anexos estão escondidos. Os boões de compartilhamento de rede social tb está escondido.

![image](https://user-images.githubusercontent.com/7662029/56385019-4e97da80-61f4-11e9-9a8f-7de33eacf77c.png)

Issue original: https://github.com/culturagovbr/portal-cultura/issues/30

**Comment by alvinodigo** [comment]
Feito.
